version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Veloci.Web/Dockerfile
    ports:
      - "${BACKEND_PORT_1}:8080"
      - "${BACKEND_PORT_2}:8081"
    volumes:
      - ./backend:/src:cached
      - ./backend/Veloci.Web/DB:/app/DB 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    working_dir: /app
    command: ["dotnet", "Veloci.Web.dll"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./frontend:/app
      - ./shared/api:/shared/api:ro
    working_dir: /app
    command: sh -c "npm install && npm run gen && npm run dev"
